[build-system]
requires = [
    "setuptools",
    "pandas",
    "networkx",
    "matplotlib",
    "wheel",
    "numpy",
    "pandas",
    "plotnine",
    "pyscipopt",
    "sympy",
    "scipy"
    ]
build-backend = "setuptools.build_meta"

